In [1]:
# Step 1. Import the necessary libraries

import pandas as pd
import numpy as np

In [2]:
# Step 2. Import the dataset

df = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data')

In [3]:
# Step 3. Assign it to a variable called wine

wine = df
wine.head()

,1,14.23,1.71,2.43,15.6,127,2.8,3.06,.28,2.29,5.64,1.04,3.92,1065
0,1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050
1,1,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185
2,1,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480
3,1,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735
4,1,14.20,1.76,2.45,15.2,112,3.27,3.39,0.34,1.97,6.75,1.05,2.85,1450

In [6]:
# Step 4. Delete the first, fourth, seventh, nineth, eleventh, thirteenth and fourteenth columns

wine.drop(wine.columns[[0, 3, 6, 8, 10, 12, 13]], axis=1)

     14.23  1.71  15.6  127  3.06  2.29  1.04
0    13.20  1.78  11.2  100  2.76  1.28  1.05
1    13.16  2.36  18.6  101  3.24  2.81  1.03
2    14.37  1.95  16.8  113  3.49  2.18  0.86
3    13.24  2.59  21.0  118  2.69  1.82  1.04
4    14.20  1.76  15.2  112  3.39  1.97  1.05
..     ...   ...   ...  ...   ...   ...   ...
172  13.71  5.65  20.5   95  0.61  1.06  0.64
173  13.40  3.91  23.0  102  0.75  1.41  0.70
174  13.27  4.28  20.0  120  0.69  1.35  0.59
175  13.17  2.59  20.0  120  0.68  1.46  0.60
176  14.13  4.10  24.5   96  0.76  1.35  0.61

[177 rows x 7 columns]

In [8]:
# Step 5. Assign the columns as below:
#The attributes are (donated by Riccardo Leardi, riclea '@' anchem.unige.it):
# 1) Alcohol
# 2) Malic acid
# 3) Ash
# 4) Alcalinity of ash
# 5) Magnesium
# 6) Total phenols
# 7) Flavanoids
# 8) Nonflavanoid phenols
# 9) Proanthocyanins
# 10)Color intensity
# 11)Hue
# 12)OD280/OD315 of diluted wines
# 13)Proline

wine.columns =['type','Alcohol', 'Malic acid', 'Ash', 'Alcalinity of ash','Magnesium','Total phenols','Flavanoids','Nonflavanoid phenols','Proanthocyanins','Color intensity','Hue','OD280/OD315 of diluted wines','Proline']

In [9]:
wine.head()

,type,Alcohol,Malic acid,Ash,Alcalinity of ash,Magnesium,Total phenols,Flavanoids,Nonflavanoid phenols,Proanthocyanins,Color intensity,Hue,OD280/OD315 of diluted wines,Proline
0,1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050
1,1,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185
2,1,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480
3,1,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735
4,1,14.20,1.76,2.45,15.2,112,3.27,3.39,0.34,1.97,6.75,1.05,2.85,1450

In [24]:
# Step 6. Set the values of the first 3 rows from alcohol as NaN

wine.loc[0:2, ['Alcohol']] = [np.nan]
wine

,type,Alcohol,Malic acid,Ash,Alcalinity of ash,Magnesium,Total phenols,Flavanoids,Nonflavanoid phenols,Proanthocyanins,Color intensity,Hue,OD280/OD315 of diluted wines,Proline
0,1.0,NaN,1.78,2.14,11.2,100.0,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050.0
2,1.0,NaN,1.95,2.50,16.8,100.0,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480.0
3,1.0,13.24,2.59,2.87,21.0,100.0,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735.0
5,1.0,14.39,1.87,2.45,14.6,96.0,2.50,2.52,0.30,1.98,5.25,1.02,3.58,1290.0
8,1.0,13.86,1.35,2.27,16.0,98.0,2.98,3.15,0.22,1.85,7.22,1.01,3.55,1045.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
172,3.0,13.71,5.65,2.45,20.5,95.0,1.68,0.61,0.52,1.06,7.70,0.64,1.74,740.0
173,3.0,13.40,3.91,2.48,23.0,102.0,1.80,0.75,0.43,1.41,7.30,0.70,1.56,750.0
174,3.0,13.27,4.28,2.26,20.0,120.0,1.59,0.69,0.43,1.35,10.20,0.59,1.56,835.0
175,3.0,13.17,2.59,2.37,20.0,120.0,1.65,0.68,0.53,1.46,9.30,0.60,1.62,840.0
176,3.0,14.13,4.10,2.74,24.5,96.0,2.05,0.76,0.56,1.35,9.20,0.61,1.60,560.0

In [12]:
# Step 7. Now set the value of the rows 3 and 4 of magnesium as NaN

wine.loc[2:3, ['Magnesium']] = [np.nan]
wine.head()

,type,Alcohol,Malic acid,Ash,Alcalinity of ash,Magnesium,Total phenols,Flavanoids,Nonflavanoid phenols,Proanthocyanins,Color intensity,Hue,OD280/OD315 of diluted wines,Proline
0,1,NaN,1.78,2.14,11.2,100.0,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050
1,1,NaN,2.36,2.67,18.6,101.0,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185
2,1,NaN,1.95,2.50,16.8,NaN,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480
3,1,13.24,2.59,2.87,21.0,NaN,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735
4,1,14.20,1.76,2.45,15.2,112.0,3.27,3.39,0.34,1.97,6.75,1.05,2.85,1450

In [23]:
# Step 8. Fill the value of NaN with the number 10 in alcohol and 100 in magnesium

wine['Alcohol'].replace(np.nan,10,inplace=True)
wine['Magnesium'].replace(np.nan,100,inplace=True)
wine

,type,Alcohol,Malic acid,Ash,Alcalinity of ash,Magnesium,Total phenols,Flavanoids,Nonflavanoid phenols,Proanthocyanins,Color intensity,Hue,OD280/OD315 of diluted wines,Proline
0,1.0,10.00,1.78,2.14,11.2,100.0,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050.0
2,1.0,10.00,1.95,2.50,16.8,100.0,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480.0
3,1.0,13.24,2.59,2.87,21.0,100.0,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735.0
5,1.0,14.39,1.87,2.45,14.6,96.0,2.50,2.52,0.30,1.98,5.25,1.02,3.58,1290.0
8,1.0,13.86,1.35,2.27,16.0,98.0,2.98,3.15,0.22,1.85,7.22,1.01,3.55,1045.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
172,3.0,13.71,5.65,2.45,20.5,95.0,1.68,0.61,0.52,1.06,7.70,0.64,1.74,740.0
173,3.0,13.40,3.91,2.48,23.0,102.0,1.80,0.75,0.43,1.41,7.30,0.70,1.56,750.0
174,3.0,13.27,4.28,2.26,20.0,120.0,1.59,0.69,0.43,1.35,10.20,0.59,1.56,835.0
175,3.0,13.17,2.59,2.37,20.0,120.0,1.65,0.68,0.53,1.46,9.30,0.60,1.62,840.0
176,3.0,14.13,4.10,2.74,24.5,96.0,2.05,0.76,0.56,1.35,9.20,0.61,1.60,560.0

In [14]:
# Step 9. Count the number of missing values

wine.isnull().sum() # no missing values

type                            0
Alcohol                         0
Malic acid                      0
Ash                             0
Alcalinity of ash               0
Magnesium                       0
Total phenols                   0
Flavanoids                      0
Nonflavanoid phenols            0
Proanthocyanins                 0
Color intensity                 0
Hue                             0
OD280/OD315 of diluted wines    0
Proline                         0
dtype: int64

In [16]:
# Step 10. Create an array of 10 random numbers up until 10


randnums= np.random.randint(1,10,10)
randnums

array([9, 4, 6, 1, 4, 7, 7, 6, 1, 7])

In [17]:
# Step 11. Use random numbers you generated as an index and assign NaN value to each of cell.

wine.loc[randnums] = np.nan
wine.head(10)

,type,Alcohol,Malic acid,Ash,Alcalinity of ash,Magnesium,Total phenols,Flavanoids,Nonflavanoid phenols,Proanthocyanins,Color intensity,Hue,OD280/OD315 of diluted wines,Proline
0,1.0,10.00,1.78,2.14,11.2,100.0,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050.0
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1.0,10.00,1.95,2.50,16.8,100.0,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480.0
3,1.0,13.24,2.59,2.87,21.0,100.0,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735.0
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,1.0,14.39,1.87,2.45,14.6,96.0,2.50,2.52,0.30,1.98,5.25,1.02,3.58,1290.0
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,1.0,13.86,1.35,2.27,16.0,98.0,2.98,3.15,0.22,1.85,7.22,1.01,3.55,1045.0
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
# Step 12. How many missing values do we have?

wine.isnull().sum()

type                            5
Alcohol                         5
Malic acid                      5
Ash                             5
Alcalinity of ash               5
Magnesium                       5
Total phenols                   5
Flavanoids                      5
Nonflavanoid phenols            5
Proanthocyanins                 5
Color intensity                 5
Hue                             5
OD280/OD315 of diluted wines    5
Proline                         5
dtype: int64

In [21]:
# Step 13. Delete the rows that contain missing values

wine.dropna(inplace=True)
wine

,type,Alcohol,Malic acid,Ash,Alcalinity of ash,Magnesium,Total phenols,Flavanoids,Nonflavanoid phenols,Proanthocyanins,Color intensity,Hue,OD280/OD315 of diluted wines,Proline
0,1.0,10.00,1.78,2.14,11.2,100.0,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050.0
2,1.0,10.00,1.95,2.50,16.8,100.0,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480.0
3,1.0,13.24,2.59,2.87,21.0,100.0,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735.0
5,1.0,14.39,1.87,2.45,14.6,96.0,2.50,2.52,0.30,1.98,5.25,1.02,3.58,1290.0
8,1.0,13.86,1.35,2.27,16.0,98.0,2.98,3.15,0.22,1.85,7.22,1.01,3.55,1045.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
172,3.0,13.71,5.65,2.45,20.5,95.0,1.68,0.61,0.52,1.06,7.70,0.64,1.74,740.0
173,3.0,13.40,3.91,2.48,23.0,102.0,1.80,0.75,0.43,1.41,7.30,0.70,1.56,750.0
174,3.0,13.27,4.28,2.26,20.0,120.0,1.59,0.69,0.43,1.35,10.20,0.59,1.56,835.0
175,3.0,13.17,2.59,2.37,20.0,120.0,1.65,0.68,0.53,1.46,9.30,0.60,1.62,840.0
176,3.0,14.13,4.10,2.74,24.5,96.0,2.05,0.76,0.56,1.35,9.20,0.61,1.60,560.0

In [22]:
# Step 14. Print only the non-null values in alcohol

wine.loc[wine['Alcohol'].notnull()]

,type,Alcohol,Malic acid,Ash,Alcalinity of ash,Magnesium,Total phenols,Flavanoids,Nonflavanoid phenols,Proanthocyanins,Color intensity,Hue,OD280/OD315 of diluted wines,Proline
0,1.0,10.00,1.78,2.14,11.2,100.0,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050.0
2,1.0,10.00,1.95,2.50,16.8,100.0,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480.0
3,1.0,13.24,2.59,2.87,21.0,100.0,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735.0
5,1.0,14.39,1.87,2.45,14.6,96.0,2.50,2.52,0.30,1.98,5.25,1.02,3.58,1290.0
8,1.0,13.86,1.35,2.27,16.0,98.0,2.98,3.15,0.22,1.85,7.22,1.01,3.55,1045.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
172,3.0,13.71,5.65,2.45,20.5,95.0,1.68,0.61,0.52,1.06,7.70,0.64,1.74,740.0
173,3.0,13.40,3.91,2.48,23.0,102.0,1.80,0.75,0.43,1.41,7.30,0.70,1.56,750.0
174,3.0,13.27,4.28,2.26,20.0,120.0,1.59,0.69,0.43,1.35,10.20,0.59,1.56,835.0
175,3.0,13.17,2.59,2.37,20.0,120.0,1.65,0.68,0.53,1.46,9.30,0.60,1.62,840.0
176,3.0,14.13,4.10,2.74,24.5,96.0,2.05,0.76,0.56,1.35,9.20,0.61,1.60,560.0

In [25]:
# Step 15. Reset the index, so it starts with 0 again

wine.reset_index(inplace = True, drop = True)
wine

,type,Alcohol,Malic acid,Ash,Alcalinity of ash,Magnesium,Total phenols,Flavanoids,Nonflavanoid phenols,Proanthocyanins,Color intensity,Hue,OD280/OD315 of diluted wines,Proline
0,1.0,NaN,1.78,2.14,11.2,100.0,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050.0
1,1.0,NaN,1.95,2.50,16.8,100.0,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480.0
2,1.0,13.24,2.59,2.87,21.0,100.0,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735.0
3,1.0,14.39,1.87,2.45,14.6,96.0,2.50,2.52,0.30,1.98,5.25,1.02,3.58,1290.0
4,1.0,13.86,1.35,2.27,16.0,98.0,2.98,3.15,0.22,1.85,7.22,1.01,3.55,1045.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
167,3.0,13.71,5.65,2.45,20.5,95.0,1.68,0.61,0.52,1.06,7.70,0.64,1.74,740.0
168,3.0,13.40,3.91,2.48,23.0,102.0,1.80,0.75,0.43,1.41,7.30,0.70,1.56,750.0
169,3.0,13.27,4.28,2.26,20.0,120.0,1.59,0.69,0.43,1.35,10.20,0.59,1.56,835.0
170,3.0,13.17,2.59,2.37,20.0,120.0,1.65,0.68,0.53,1.46,9.30,0.60,1.62,840.0
171,3.0,14.13,4.10,2.74,24.5,96.0,2.05,0.76,0.56,1.35,9.20,0.61,1.60,560.0

In [ ]:
#